In [ ]:
import pandas as pd
import matplotlib as mpl

In [ ]:
df = pd.read_json("dataset.json", lines = True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201716 entries, 0 to 201715
Data columns (total 10 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   email        201716 non-null  object
 1   first_name   201716 non-null  object
 2   gender       201716 non-null  object
 3   last_name    201716 non-null  object
 4   order_date   201716 non-null  object
 5   order_id     201716 non-null  object
 6   order_items  201716 non-null  object
 7   phone        201716 non-null  object
 8   state        201716 non-null  object
 9   zip          201716 non-null  int64
dtypes: int64(1), object(9)
memory usage: 15.4+ MB

In [ ]:
df.head()

,email,first_name,gender,last_name,order_date,order_id,order_items,phone,state,zip
0,jani.titus@gmail.com,Jani,F,Titus,01-10-2020,100354678,"[{'discount_amount': '0', 'price': '89.9', 'pr...",405-959-1129,OK,73571
1,jason.simoneau@gmail.com,Jason,M,Simoneau,25-10-2020,100359558,"[{'discount_amount': '0', 'price': '199.9', 'p...",701-522-6439,ND,58201
2,grover.bayless@yahoo.com,Grover,M,Bayless,16-10-2020,100357608,"[{'discount_amount': '0', 'price': '1543.5', '...",808-380-3891,HI,96764
3,grover.bayless@yahoo.com,Grover,M,Bayless,17-10-2020,100358002,"[{'discount_amount': '0', 'price': '1543.5', '...",808-380-3891,HI,96764
4,elizbeth.raminez@gmail.com,Elizbeth,F,Raminez,01-10-2020,100354692,"[{'discount_amount': '0', 'price': '35', 'prod...",217-405-0048,IL,62418

In [ ]:
df = df.explode("order_items")

#Convierte cada diccionario en columnas
items = pd.json_normalize(df["order_items"])

#Une las nuevas columnas con el resto del DataFrame
df = pd.concat([df.drop(columns=["order_items"]).reset_index(drop=True),
                items.reset_index(drop=True)],
               axis=1)

In [ ]:
#Renombramos las columnas para mejor comprension

df = df.rename(columns={
    "email": "correo",
    "first_name": "nombre",
    "gender": "genero",
    "last_name": "apellidos",
    "order_date": "fecha_pedido",
    "order_id": "id_pedido",
    "phone": "telefono",
    "state": "estado",
    "zip": "codigo_postal",
    "discount_amount": "descuento",
    "price": "precio",
    "product_category": "categoria_producto",
    "qty_ordered": "cantidad",
    "sku": "sku"
})
df.head()

,correo,nombre,genero,apellidos,fecha_pedido,id_pedido,telefono,estado,codigo_postal,descuento,precio,categoria_producto,cantidad,sku
0,jani.titus@gmail.com,Jani,F,Titus,01-10-2020,100354678,405-959-1129,OK,73571,0,89.9,Men's Fashion,21,oasis_Oasis-064-36
1,jani.titus@gmail.com,Jani,F,Titus,01-10-2020,100354678,405-959-1129,OK,73571,0,19,Men's Fashion,11,Fantastic_FT-48
2,jason.simoneau@gmail.com,Jason,M,Simoneau,25-10-2020,100359558,701-522-6439,ND,58201,0,199.9,Appliances,11,APPLIO59BA25191179A
3,grover.bayless@yahoo.com,Grover,M,Bayless,16-10-2020,100357608,808-380-3891,HI,96764,0,1543.5,Appliances,2,APPHAI59ACA3A653D02
4,grover.bayless@yahoo.com,Grover,M,Bayless,17-10-2020,100358002,808-380-3891,HI,96764,0,1543.5,Appliances,2,APPHAI59ACA3A653D02

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286392 entries, 0 to 286391
Data columns (total 14 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   correo              286392 non-null  object
 1   nombre              286392 non-null  object
 2   genero              286392 non-null  object
 3   apellidos           286392 non-null  object
 4   fecha_pedido        286392 non-null  object
 5   id_pedido           286392 non-null  object
 6   telefono            286392 non-null  object
 7   estado              286392 non-null  object
 8   codigo_postal       286392 non-null  int64
 9   descuento           286392 non-null  object
 10  precio              286392 non-null  object
 11  categoria_producto  286392 non-null  object
 12  cantidad            286392 non-null  object
 13  sku                 286392 non-null  object
dtypes: int64(1), object(13)
memory usage: 30.6+ MB

In [ ]:
#Parseamos los campos al formato correspondiente

df["fecha_pedido"] = pd.to_datetime(df["fecha_pedido"],format="%d-%m-%Y")
df["codigo_postal"] = df["codigo_postal"].astype(str)
df["descuento"] = df["descuento"].astype(float)
df["precio"] = df["precio"].astype(float)
df["cantidad"] = df["cantidad"].astype(int)

In [ ]:
#Verificamos que el parseo se ha aplicado correctamente

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 286392 entries, 0 to 286391
Data columns (total 14 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   correo              286392 non-null  object
 1   nombre              286392 non-null  object
 2   genero              286392 non-null  object
 3   apellidos           286392 non-null  object
 4   fecha_pedido        286392 non-null  datetime64[ns]
 5   id_pedido           286392 non-null  object
 6   telefono            286392 non-null  object
 7   estado              286392 non-null  object
 8   codigo_postal       286392 non-null  object
 9   descuento           286392 non-null  float64
 10  precio              286392 non-null  float64
 11  categoria_producto  286392 non-null  object
 12  cantidad            286392 non-null  int64
 13  sku                 286392 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(10)
memory usage: 30.6+ MB

In [ ]:
df.head()

,correo,nombre,genero,apellidos,fecha_pedido,id_pedido,telefono,estado,codigo_postal,descuento,precio,categoria_producto,cantidad,sku
0,jani.titus@gmail.com,Jani,F,Titus,2020-10-01,100354678,405-959-1129,OK,73571,0.0,89.9,Men's Fashion,21,oasis_Oasis-064-36
1,jani.titus@gmail.com,Jani,F,Titus,2020-10-01,100354678,405-959-1129,OK,73571,0.0,19.0,Men's Fashion,11,Fantastic_FT-48
2,jason.simoneau@gmail.com,Jason,M,Simoneau,2020-10-25,100359558,701-522-6439,ND,58201,0.0,199.9,Appliances,11,APPLIO59BA25191179A
3,grover.bayless@yahoo.com,Grover,M,Bayless,2020-10-16,100357608,808-380-3891,HI,96764,0.0,1543.5,Appliances,2,APPHAI59ACA3A653D02
4,grover.bayless@yahoo.com,Grover,M,Bayless,2020-10-17,100358002,808-380-3891,HI,96764,0.0,1543.5,Appliances,2,APPHAI59ACA3A653D02

In [ ]:
####Analizamos que las variables numéricas no tengan valores erróneos (como números en negativo)
df[["descuento","precio","cantidad"]].describe()

           descuento         precio       cantidad
count  286392.000000  286392.000000  286392.000000
mean       70.039427     851.385253       3.011296
std       256.880870    1741.750751       4.573837
min         0.000000       0.000000       1.000000
25%         0.000000      49.900000       2.000000
50%         0.000000     119.000000       2.000000
75%        18.383050     950.000000       3.000000
max     30213.150000  101262.590000     501.000000

In [ ]:
####Añadimos campso de interés para el análisis

#El importe, que se obtiene multiplicando el precio unitario por la cantidad

df["importe"] = df["precio"]*df["cantidad"]

In [ ]:
df.head()

,correo,nombre,genero,apellidos,fecha_pedido,id_pedido,telefono,estado,codigo_postal,descuento,precio,categoria_producto,cantidad,sku,importe
0,jani.titus@gmail.com,Jani,F,Titus,2020-10-01,100354678,405-959-1129,OK,73571,0.0,89.9,Men's Fashion,21,oasis_Oasis-064-36,1887.9
1,jani.titus@gmail.com,Jani,F,Titus,2020-10-01,100354678,405-959-1129,OK,73571,0.0,19.0,Men's Fashion,11,Fantastic_FT-48,209.0
2,jason.simoneau@gmail.com,Jason,M,Simoneau,2020-10-25,100359558,701-522-6439,ND,58201,0.0,199.9,Appliances,11,APPLIO59BA25191179A,2198.9
3,grover.bayless@yahoo.com,Grover,M,Bayless,2020-10-16,100357608,808-380-3891,HI,96764,0.0,1543.5,Appliances,2,APPHAI59ACA3A653D02,3087.0
4,grover.bayless@yahoo.com,Grover,M,Bayless,2020-10-17,100358002,808-380-3891,HI,96764,0.0,1543.5,Appliances,2,APPHAI59ACA3A653D02,3087.0

In [ ]:

##Agrupamos los pedidos y los clientes para obtener las métricas, usando "first" en lso campos que se repiten en los pedidos (en este caso, correo y estado)
pedidos = (df.groupby("id_pedido")
             .agg(correo=("correo", "first"),
                  fecha_pedido=("fecha_pedido", "min"),
                  estado=("estado", "first"),
                  importe_pedido=("importe", "sum"))
             .reset_index())

#Ordenamos por correo y por fecha de pedido
pedidos = pedidos.sort_values(["correo", "fecha_pedido"])

#Creamos un índice para identificar cada fila
pedidos["num_pedido_cliente"] = pedidos.groupby("correo").cumcount() + 1

##Hacemos lo mismo con los clientes
clientes = (pedidos.groupby("correo")
                    .agg(num_pedidos=("id_pedido", "count"),
                         fecha_adquisicion=("fecha_pedido", "min"),
                         estado=("estado", "first"))
                    .reset_index())
#Identificamos a los clientes recurrentes
clientes["es_recurrente"] = clientes["num_pedidos"] > 1

#Generamos el desglose de clientes por año y mes de adquisición
clientes["clientes_mes_año"] = clientes["fecha_adquisicion"].dt.to_period("M").astype(str)

In [ ]:
# Separamos los pedidos en "primeros" y "recurrentes"
primeros = pedidos[pedidos["num_pedido_cliente"] == 1]
recurrentes = pedidos[pedidos["num_pedido_cliente"] > 1]
clientes = clientes.merge(
    primeros.rename(columns={"importe_pedido": "importe_primer_pedido"})
            [["correo", "importe_primer_pedido"]], on="correo", how="left")

#Importe de los pedidos recurrentes
importe_recurrente = (recurrentes.groupby("correo")["importe_pedido"].sum()
                                  .rename("importe_total_recurrente").reset_index())
clientes = clientes.merge(importe_recurrente, on="correo", how="left")
clientes["importe_total_recurrente"] = clientes["importe_total_recurrente"].fillna(0)

# Tiempo medio entre recurrencias
pedidos["dias_desde_anterior"] = pedidos.groupby("correo")["fecha_pedido"].diff().dt.days

#Filtramos para no incluir los días anteriores iguales a 0 (aquellos pedidos hechos en el mismo días) para no distorsionar la media"
pedidos["dias_desde_anterior_sin_sameday"] = pedidos["dias_desde_anterior"].where(
    pedidos["dias_desde_anterior"] > 0)

#Se calculan ambas métricas para comparar
tiempo_medio = (pedidos.groupby("correo")
                        .agg(
                            tiempo_medio_recurrencia_dias=("dias_desde_anterior", "mean"),
                            tiempo_medio_sin_sameday=("dias_desde_anterior_sin_sameday", "mean")
                            ))
                        .reset_index())

#Añadimos el tiempo medio a la tabla de clientes
clientes = clientes.merge(tiempo_medio, on="correo", how="left")

In [ ]:
df.to_csv("dataset_limpio.csv")
pedidos.to_csv("pedidos.csv")
clientes.to_csv("clientes.csv")